INSERT INTO carport.materials VALUES 
('1','Trykimp. brædt length: 360cm, height: 200cm, width: 25cm, enhed: stk, understærnbredder til for og bag ende'),
('2','Trykimp. brædt length: 540cm, height: 200cm, width: 25cm, enhed: stk, understærnbredder til siderne'),
('3','Trykimp. brædt length: 360cm, height: 125cm, width: 25cm, enhed: stk, overstærnbredder til forenden'),
('4','Trykimp. brædt length: 540cm, height: 125cm, width: 25cm, enhed: stk, overstærnbredder til siderne'),
('5','Lægte ubh. length: 420cm, height: 73cm, width: 38cm, enhed: stk, til z på bagside af dør'),
('6','Reglar ub. length: 270cm, height: 95cm, width: 45cm, enhed: stk, løsholter til skur gavle'),
('7','Reglar ub. length: 240cm, height: 95cm, width: 45cm, enhed: stk, løsholter til skur sider'),
('8','Spærtræ ubh. length: 600cm, height: 195cm, width: 45cm, enhed: stk, Remme i sider, sadles ned i stolper'),
('9','Spærtræ ubh. length: 480cm, height: 195cm, width: 45cm, enhed: stk, Remme i sider, sadles ned i stolper (skur del, deles)'),
('10','Spærtræ ubh. length: 600cm, height: 195cm, width: 45cm, enhed: stk, Remme i sider, spær, monteres på rem'),
('11','Trykimp. stolpe length: 300cm, height: 97cm, width: 97cm, enhed: stk, Remme i sider, stolper nedgraves 90 cm. i jord'),
('12','Trykimp. brædt length: 210cm, height: 100cm, width: 19cm, enhed: stk, til beklædning af skur 1 på 2'),
('13','Trykimp. brædt length: 540cm, height: 100cm, width: 19cm, enhed: stk, vandbrædt på stern i sider'),
('14','Trykimp. brædt length: 360cm, height: 100cm, width: 19cm, enhed: stk, vandbrædt på stern i forende'),
('15','Plastmo Ecolite blåtonet length: 600cm, enhed: stk, tagplader monteres på spær'),
('16','Plastmo Ecolite blåtonet length: 360cm, enhed: stk, tagplader monteres på spær'),
('17','Plastmo bundskruer, 200 pr. pakke, enhed: pakke, skruer til tagplade'),
('18','Hulbånd, 1x20mm, 10m rulle, enhed: rulle,  til vindkryds på spær'),
('19','Universal 190mm højre, enhed: stk, til montering af spær på rem'),
('20','Universal 190mm venstre, enhed: stk, til montering af spær på rem'),
('21','Skruer 4,5x60mm, 200 pr. pakke, enhed: pakke, til montering af stern of vandbrædt'),
('22','Beslagskruer 4x50mm, 250 pr. pakke, enhed: pakke, til montering af universalbeslag og hulbånd'),
('23','Bræddebolt 10x120mm, enhed: stk, til montering af rem på stolper'),
('24','Firkantskiver 40x40x11mm, enhed: stk, til montering af rem på stolper'),
('25','Skruer 4,5x70mm, 400 pr. pakke, enhed: pakke, til montering af yderste beklædning'),
('26','Skruer 4,5x50mm, 300 pr. pakke, enhed: pakke, til montering af inderste beklædning'),
('27','Stalddørsgreb 50x75, enhed: sæt, til lås på dør i skur'),
('28','T hængsel 390mm, enhed: stk, til skurdør'),
('28','Vinkelbeslag 35, enhed: stk, til montering af løsholter i skur');



