INSERT INTO carport.materials VALUES 
('1','Trykimp. brædt length: 360mm, height: 200mm, width: 25mm, enhed: stk, understærnbredder til for og bag ende'),
('2','Trykimp. brædt length: 540mm, height: 200mm, width: 25mm, enhed: stk, understærnbredder til siderne'),
('3','Trykimp. brædt length: 360mm, height: 125mm, width: 25mm, enhed: stk, overstærnbredder til forenden'),
('4','Trykimp. brædt length: 540mm, height: 125mm, width: 25mm, enhed: stk, overstærnbredder til siderne'),
('5','Lægte ubh. length: 420mm, height: 73mm, width: 38mm, enhed: stk, til z på bagside af dør'),
('6','Reglar ub. length: 270mm, height: 95mm, width: 45mm, enhed: stk, løsholter til skur gavle'),
('7','Reglar ub. length: 240mm, height: 95mm, width: 45mm, enhed: stk, løsholter til skur sider'),
('8','Spærtræ ubh. length: 600mm, height: 195mm, width: 45mm, enhed: stk, Remme i sider, sadles ned i stolper'),
('9','Spærtræ ubh. length: 480mm, height: 195mm, width: 45mm, enhed: stk, Remme i sider, sadles ned i stolper (skur del, deles)'),
('10','Spærtræ ubh. length: 600mm, height: 195mm, width: 45mm, enhed: stk, Remme i sider, spær, monteres på rem'),
('11','Trykimp. stolpe length: 300mm, height: 97mm, width: 97mm, enhed: stk, Remme i sider, stolper nedgraves 90 cm. i jord'),
('12','Trykimp. brædt length: 210mm, height: 100mm, width: 19mm, enhed: stk, til beklædning af skur 1 på 2'),
('13','Trykimp. brædt length: 540mm, height: 100mm, width: 19mm, enhed: stk, vandbrædt på stern i sider'),
('14','Trykimp. brædt length: 360mm, height: 100mm, width: 19mm, enhed: stk, vandbrædt på stern i forende'),
('15','Plastmo Ecolite blåtonet length: 600mm, enhed: stk, tagplader monteres på spær'),
('16','Plastmo Ecolite blåtonet length: 360mm, enhed: stk, tagplader monteres på spær'),
('17','Plastmo bundskruer, 200 pr. pakke, enhed: pakke, skruer til tagplade'),
('18','Hulbånd, 1x20mm, 10m rulle, enhed: rulle,  til vindkryds på spær'),
('19','Universal 190mm højre, enhed: stk, til montering af spær på rem'),
('20','Universal 190mm venstre, enhed: stk, til montering af spær på rem'),
('21','Skruer 4,5x60mm, 200 pr. pakke, enhed: pakke, til montering af stern of vandbrædt'),
('22','Beslagskruer 4x50mm, 250 pr. pakke, enhed: pakke, til montering af universalbeslag og hulbånd'),
('23','Bræddebolt 10x120mm, enhed: stk, til montering af rem på stolper'),
('24','Firkantskiver 40x40x11mm, enhed: stk, til montering af rem på stolper'),
('25','Skruer 4,5x70mm, 400 pr. pakke, enhed: pakke, til montering af yderste beklædning'),
('26','Skruer 4,5x50mm, 300 pr. pakke, enhed: pakke, til montering af inderste beklædning'),
('27','Stalddørsgreb 50x75, enhed: sæt, til lås på dør i skur'),
('28','T hængsel 390mm, enhed: stk, til skurdør'),
('28','Vinkelbeslag 35, enhed: stk, til montering af løsholter i skur');



